# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad5f99b5c686e6b52b02699f9c7d044d3a5c3ed442bc08215551da368075b3ec549ce85d9873f82bac72d46616e76d84885f07288cb19c0f053ab855d5e20df

test:
  secret_key_base: b3413d234887c134ae616b584c8c255906c99b7e3a5b86953fdeb623b313c652c9da42c65f7fc1b43a91b968ea065960c4cafb42161f50d1c5a356e0e675bdc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
